remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 


title: Розробка автоматизованої інформаційної системи
«Облік клієнтів ставку»
description: «Кваліфікаційна
робота на підтвердження ступеня фахового молодшого бакалавра (ВСП
«ППФК НТУ «ХПІ»).
